openapi: 3.0.3
info:
  title: Chat App -
  description: |-
    The Real-Time Chat Application is a secure and interactive platform that allows
    users to engage in real-time conversations. With its authentication functionality
    and integration of JWT tokens, users can create accounts, log in securely, and
    access the chat features. Leveraging the power of WebSockets, the application
    provides seamless real-time communication between users, ensuring instant message
    delivery and an immersive chat experience.

    Some useful links:
    - [The Chat App Repository](https://github.com/manttus/chat_react)
  contact:
    email: basnetraymonn@gmail.com
  version: 1.0.0
servers:
  - url: https://chat-react-dmcd.onrender.com/chat-app/api/v1/
  - url: http://localhost:5000/chat-app/api/v1/
tags:
  # - name: User
  #   description: Operation for Users
  - name: Authentication
    description: Authentication for Users
  - name: OTP
    description: One Time Passwords for Users
  - name: User
    description: User Configurations
paths:
  /user/delete:
    delete:
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "User Removed"
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
        "401":
          description: UnAuthorized
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "UnAuthorized"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"
  /user/update:
    put:
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "User Updated"
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"

        "401":
          description: UnAuthorized
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "UnAuthorized"

        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"
  /user/profile:
    get:
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  email:
                    example: "basnetraymonn@gmail.com"
                    type: string
                  image:
                    example: "https://brrrrrrr.png"
                    type: string
                  username:
                    example: "mantuu"
                    type: string
                  groups:
                    type: array
                    items:
                      example: "69696969"
                      type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"

        "401":
          description: UnAuthorized
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "UnAuthorized"

        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"

  /otp/verifyLink/{hash}:
    get:
      tags:
        - OTP
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Verified"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"

        "401":
          description: UnAuthorized
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "UnAuthorized"

        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"
  /otp/sendOtp:
    post:
      tags:
        - OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  title: email
                  example: basnetraymonn@gmail.com
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Sent"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"

        "409":
          description: Conflict Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Already Sent"

        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"
  /otp/authOtp:
    post:
      tags:
        - OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  title: email
                  example: basnetraymonn@gmail.com
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Sent"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
  /otp/verifyOtp:
    post:
      tags:
        - OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  title: email
                  example: basnetraymonn@gmail.com
                  type: string
                otp:
                  title: otp
                  example: 956740
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Verified"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
        "409":
          description: Conflict Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Email Already Sent"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: "Internal Server Error"

  /auth/login:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  title: email
                  example: basnetraymonn@gmail.com
                  type: string
                password:
                  title: password
                  example: 73-55-608Cyka
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  access:
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj
                    type: string
                  refresh:
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Server Error"
  /auth/register:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  title: username
                  example: mantuu
                  type: string
                email:
                  title: email
                  example: basnetraymonn@gmail.com
                  type: string
                password:
                  title: password
                  example: 73-55-608Cyka
                  type: string

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  access:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj
                  refresh:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Server Error"
  /auth/token:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                token:
                  title: token
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj
                  type: string

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  access:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlcm5hbWUiOiJleGFtcGxlVXNlciIsImlhdCI6MTYyMzIxMDc2MSwiZXhwIjoxNjIzMj

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Server Error"
  /auth/reset:
    patch:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  title: email
                  example: basnetraymonn@gmail.com

                new_password:
                  title: password
                  example: 73-55-608
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Password Updated"

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid Credentials"
                  error:
                    example:
                      type: "field"
                      value: ""
                      msg: "Field cannot be empty"
                      path: "email"
                      location: "body"
                    nullable: true
                    description: "This field can be undefined"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Server Error"
